### ISSUE TITLE
The Icon does not look sharp when in hidpi mode

### ISSUE THREAD

**Issue by 183amir** [tiwoc/fxdpi#1]
Here is a screen shot:
![screenshot from 2015-05-07 20-35-16](https://cloud.githubusercontent.com/assets/5738695/7514491/bfc56ab4-f4f8-11e4-9f1f-93dfafa06449.png)

As you can see other icons look sharp but not this one.

**Comment by tiwoc** [comment]
You're right, this looks ugly. I just pushed an update that exchanges the PNG icons in three different sizes with an SVG icon that can be scaled to an arbitrary size. This seems to be supported by Firefox but I haven't found any documentation on the supported file formats: Only PNG is mentioned in the addon docs...

You should get the update as soon as the change has been reviewed by a Mozilla volunteer.

**Comment by 183amir** [comment]
Thank you! It looks good now.
Can I suggest a more simple icon like this:
![fxdpi](https://cloud.githubusercontent.com/assets/5738695/7554703/79b8cd14-f76d-11e4-9116-c8f5a7590ef4.png)
I can give the source file to you if you like it.

**Comment by tiwoc** [comment]
Sorry for letting you wait for so long :(

I would be very much interested in using the simpler icon in the next version. Could you send me an SVG version of the icon or open a pull request that replaces the icon?

Additionally, I need your consent to share the icon under the terms of [CC-BY](http://creativecommons.org/licenses/by/4.0/) or preferrably [CC0](http://creativecommons.org/publicdomain/zero/1.0/) so that it can be used as freely as the rest of the extension, which is MIT licensed.

**Comment by 183amir** [comment]
There you go: `https://www.mediafire.com/?1gkg1nyfrpwgc8z`
You might wanna increase the thickness of the lines.
You can use this freely for any purpose without any license.
